all:
	g++ -march=native -O3 -o example example.cpp
	./example
json:
	g++ -O3 -march=native example_json.cpp -o example_json
	./example_json
uscalec:
	g++ -O3 -march=native example_uscalec.cpp -o example_uscalec
	./example_uscalec