all:
	g++ example_test.cpp -o example_test
	./example_test
mod:
	g++ example_mod_test.cpp -o example_mod_test
	./example_mod_test
fixed:
	g++ example_fixed_test.cpp -o example_fixed_test
	./example_fixed_test